name: Deploy for testing

on:
  workflow_dispatch:   

env:
  CONTAINER_NAME: ${{ vars.CONTAINER_NAME }}
  CR_PAT: ${{ vars.CR_PAT }}
  CR_USER: threedradio

jobs:
  build:
    environment: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/$CR_USER/$CONTAINER_NAME:testing
      
    - name: Login to the GitHub Docker registry
      run: echo $CR_PAT | docker login ghcr.io -u $CR_USER --password-stdin
      
    - name: Push the Docker image to ghcr.io
      run: docker push ghcr.io/$CR_USER/$CONTAINER_NAME:testing

    - name: Execute remote SSH commands using SSH key
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: | 
          whoami
          docker stop ${{ vars.CONTAINER_NAME }}
          docker container rm ${{ vars.CONTAINER_NAME }}
          docker pull ghcr.io/${{ vars.CR_PAT }}/${{ vars.CONTAINER_NAME }}:testing
          docker run -p 9000:80 -p 9001:443 --name ${{ vars.CONTAINER_NAME }} -d -t ghcr.io/${{ vars.CR_PAT }}/${{ vars.CONTAINER_NAME }}:testing
